---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/25 20:47
---
-- 得到锁的key
-- local key = KEYS[1]

-- 当前线程表示
-- local threadId = ARGV[1]

-- 获取锁中的线程表示
local id = redis.call('get', KEYS[1])

-- 判断是否与指定的表示一致
if(id == ARGV[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end

return 0